preprocessing:
    lower: True
    word_tokenizer: portuguese_tokenize

input_features:
  -
    name: Enunciado
    type: text
    level: word
    encoder: rnn
    cell_type: lstm
    num_layers: 2
    bidirectional: True
    attention: luong
    dropout: true

output_features:
  -
    name: Area
    type: category
    top_k: 10
  -
    name: Tema
    type: category
    top_k: 10
    dependencies:
      - Area
  -
    name: Subtema
    type: category
    top_k: 10
    dependencies:
      - Tema


training:
    batch_size: 128
    dropout_rate: 0.5
#    validation_field: Area
    validation_measure: accuracy
    early_stop: 15
